### PR TITLE
First attempt at getting it to compile again on Linux

### PR DESCRIPTION
**Pull request by peternewman**
Work towards #25

### CODE REVIEW

**Comment by peternewman** [comment]
llrp_manager_example seems to generally work fine here, LLRP parts of rdmnet_device_example also function when it's added to the build.

**Comment by samkearney** [comment]
Thanks for this work Peter. Just FYI, we were planning to use the native Avahi APIs rather than the Bonjour compat layer for the Linux port, and we're also in the middle of a bit of an API rewrite, so this might end up being a tough merge.

**Comment by peternewman** [comment]
> Thanks for this work Peter. Just FYI, we were planning to use the native Avahi APIs rather than the Bonjour compat layer for the Linux port,

Yeah that makes lots of sense, I simply picked the Bonjour option as the Avahi one wouldn't compile and this seemed like the quickest win.

> and we're also in the middle of a bit of an API rewrite, so this might end up being a tough merge.

I'm guessing that's why Avahi wasn't working, it seemed to have lots of function calls that were different to the Bonjour one.

TBH, I just wanted something that compiled on a platform I could easily run on to give me half of the problem so I could work on integrating LLRP initially, and eventually the full standardised E1.33 stack into OLA (or at least updating our existing code to match the released standard). FWIW my work in that regard is here (as expected I've not yet found any differences between the ETC implementation and the standard):
https://github.com/OpenLightingProject/ola/pull/1612

**Comment by samkearney** [comment]
We've re-ported the library to Linux as of the latest label, v0.3.0.10 (#25). This should no longer be necessary.

**Comment by peternewman** [comment]
Ooh thanks @samkearney . I'll give that a go later!

**Pull request closed without merging**
