### PR TITLE
Azure pipelines

### PR DESCRIPTION
**Pull request by ChristianReese**

### CODE REVIEW

**Comment by bootress** [comment]
I turned the Appveyor builds off, so the next push should not trigger one.

**Comment by bootress** [comment]
Replace the Appveyor badge in README.md with an Azure Pipelines one: https://poanchen.github.io/blog/2019/07/12/How-to-add-Azure-Pipelines-badge-to-your-repository-s-README-in-GitHub

**Comment by ChristianReese** [comment]
> Replace the Appveyor badge in README.md with an Azure Pipelines one: https://poanchen.github.io/blog/2019/07/12/How-to-add-Azure-Pipelines-badge-to-your-repository-s-README-in-GitHub

Done. It will show the status of develop branch builds.

**Comment by ChristianReese** [comment]
@bootress All changes have been made. I also tested the Qt download/install and that still works. Anything else to be done, or is this ready to merge?

**Pull request merged**
